Fix RestartStrategy::timeout < 1s
bastion-rs/bastion pull request #265
Opened 2020-08-19 07:32 UTC by nicolaiunrein

Fix issue where fractions of a second are ignored internally. This leads to a broken `RestartStrategy` when given a timeout of eg. `Duration::from_millis(999)`. NOTE: The type casting of `multiplier` can get removed but that would be a breaking change. I leave this for the reviewer to decide.

##### Checklist

- [x] tests are passing with `cargo test`. 
- [ ] tests and/or benchmarks are included
- [x] commit message is clear

2020-08-19 08:21 UTC, o0Ignition0o commented
Hey, thanks a lot for the pull request!

In our first implementation, we hadn't thought of a timeout < 1 sec, so that's a very welcome patch!

I'll leave it up to Relrin to review the changes, because I think he's been working on it the most.

He might be able to decide whether we wanna make a breaking change (there's a lot of things happening on the executor side, so we might wanna bump both at the same time).

Thanks again!

2020-08-19 16:11 UTC, Relrin requested changes
Changing the `multiplier` / `restarts_count` field types in the `RestartStrategy` structure to the `u32` type will eliminate type converstions.

2020-08-20 09:23 UTC, Relrin approved these changes

2020-08-20 09:25 UTC, nicolaiunrein commented
I applied the suggested changes please have a look.
I realized that after all `f64` might actually be what we want for multiplier because with an integer we are not able to increase the delay by eg. 10% on each try. The downside is that this will generate more changes:
 1. users need to change eg. `1` -> `1.0`
 2. need to remove impl of `Eq`  for ActorRestartStrategy and RestartStrategy

So feel free to undo the last commit.

2020-08-20 09:43 UTC, Relrin commented
> I realized that after all `f64` might actually be what we want for multiplier because with an integer we are not able to increase the delay by eg. 10% on each try. The downside is that this will generate more changes:
> 
> 1. users need to change eg. `1` -> `1.0`
> 2. need to remove impl of `Eq`  for ActorRestartStrategy and RestartStrategy
> 
In practice this is a quite rare case, and for the most users is more than enough to have a delay calculated with integer values. So, I think it's reasonable to left it as it for now :)

2020-08-20 09:43 UTC, o0Ignition0o commented
I think we're a cargo fmt away from merging it ! 🎉

2020-08-20 10:54 UTC, nicolaiunrein commented
Do you want me to revert to u32?

2020-08-20 11:30 UTC, Relrin commented
Yes, please, revert it back to the u32 type

2020-08-20 12:33 UTC, o0Ignition0o approved these changes

2020-08-20 19:14 UTC, o0Ignition0o commented
Amazing, thanks a lot for your contribution! 🎉

2020-08-20 19:14 UTC, merged